In [124]:
import torch
import numpy as np

In [125]:
a = torch.tensor([1,2,3])
b= np.array([1,2,3])

In [126]:
print(a)
print(b)

tensor([1, 2, 3])
[1 2 3]


In [127]:
points = torch.tensor([[2,3], [3,0.5]])

In [128]:
points

tensor([[2.0000, 3.0000],
        [3.0000, 0.5000]])

In [129]:
points.shape

torch.Size([2, 2])

In [130]:
t1 = torch.ones(size=(5,3,3))
t2 = torch.zeros(size=(3,2))
t3 = torch.arange(10)

In [131]:
print(t1)
print(t2)
print(t3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [132]:
t1[:, 2, 2]

tensor([1., 1., 1., 1., 1.])

In [133]:
t4 = torch.rand(size=(3,3,4))

In [134]:
print(t4)

tensor([[[0.9867, 0.7142, 0.0796, 0.2992],
         [0.6871, 0.4004, 0.3032, 0.7394],
         [0.1408, 0.8917, 0.8706, 0.0961]],

        [[0.8026, 0.3360, 0.6577, 0.3676],
         [0.0609, 0.1599, 0.5088, 0.2573],
         [0.8441, 0.8892, 0.7977, 0.3876]],

        [[0.3202, 0.8156, 0.3569, 0.6656],
         [0.5995, 0.2875, 0.1511, 0.1257],
         [0.8737, 0.9205, 0.8199, 0.9882]]])


In [135]:
t4[:, 2, 3]

tensor([0.0961, 0.3876, 0.9882])

# Creating Tensors from existing data

In [136]:
import numpy as np

In [137]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor(np.array([1,2,3,4,5]))
t3 = torch.tensor(np.random.randn(3))
t4 = t3.clone().detach() # from exisiting torch tensor
t4[2] = 4

In [138]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1, 2, 3])
tensor([1, 2, 3, 4, 5], dtype=torch.int32)
tensor([-0.4346,  1.0574, -1.7242], dtype=torch.float64)
tensor([-0.4346,  1.0574,  4.0000], dtype=torch.float64)


## convert tensor to numpy

In [139]:
t1 = torch.tensor([1,2,3,45])
t2 = t1.detach().numpy()

In [140]:
print(type(t2))

<class 'numpy.ndarray'>


## Accessing data within tensor

In [141]:
t = torch.rand(size=(3,2,4))
print('Org Tensor')
print(t)
print('\n')


# valid ways of accessing individual elements
print('t[0][0][0] = ', t[0][0][0])
print('t[2,1,3] = ', t[2,1,3])
print('t[-1,-1][-1] =', t[-1,-1][-1])
print('\n')


# Tensor Slicing
print('t[0] -- ', t[0])
print('t[:1] -- ', t[:1])
print('t[:,:,2] -- ', t[:,:,2])

Org Tensor
tensor([[[0.9386, 0.6012, 0.5303, 0.7843],
         [0.8394, 0.4244, 0.4194, 0.1063]],

        [[0.3133, 0.3022, 0.3979, 0.7755],
         [0.2900, 0.1487, 0.4358, 0.0227]],

        [[0.0964, 0.1017, 0.2687, 0.8158],
         [0.1051, 0.6783, 0.4959, 0.2609]]])


t[0][0][0] =  tensor(0.9386)
t[2,1,3] =  tensor(0.2609)
t[-1,-1][-1] = tensor(0.2609)


t[0] --  tensor([[0.9386, 0.6012, 0.5303, 0.7843],
        [0.8394, 0.4244, 0.4194, 0.1063]])
t[:1] --  tensor([[[0.9386, 0.6012, 0.5303, 0.7843],
         [0.8394, 0.4244, 0.4194, 0.1063]]])
t[:,:,2] --  tensor([[0.5303, 0.4194],
        [0.3979, 0.4358],
        [0.2687, 0.4959]])


## Flatten Tensor

In [142]:
print(t.flatten())

tensor([0.9386, 0.6012, 0.5303, 0.7843, 0.8394, 0.4244, 0.4194, 0.1063, 0.3133,
        0.3022, 0.3979, 0.7755, 0.2900, 0.1487, 0.4358, 0.0227, 0.0964, 0.1017,
        0.2687, 0.8158, 0.1051, 0.6783, 0.4959, 0.2609])


## Squeeze and Unsqueeze 

These commands are used to add or remove a dimension from a tensor.

In [143]:
# unsqueeze adds a dimension to the tensor...
ts = t.unsqueeze(0)
ts2 = t.unsqueeze(1)

In [144]:
print(ts.shape)
print(ts2.shape)
print('ts---', ts)
print('ts2 -- ', ts2)

torch.Size([1, 3, 2, 4])
torch.Size([3, 1, 2, 4])
ts--- tensor([[[[0.9386, 0.6012, 0.5303, 0.7843],
          [0.8394, 0.4244, 0.4194, 0.1063]],

         [[0.3133, 0.3022, 0.3979, 0.7755],
          [0.2900, 0.1487, 0.4358, 0.0227]],

         [[0.0964, 0.1017, 0.2687, 0.8158],
          [0.1051, 0.6783, 0.4959, 0.2609]]]])
ts2 --  tensor([[[[0.9386, 0.6012, 0.5303, 0.7843],
          [0.8394, 0.4244, 0.4194, 0.1063]]],


        [[[0.3133, 0.3022, 0.3979, 0.7755],
          [0.2900, 0.1487, 0.4358, 0.0227]]],


        [[[0.0964, 0.1017, 0.2687, 0.8158],
          [0.1051, 0.6783, 0.4959, 0.2609]]]])


In [145]:
#Squeeze operation does the oposite, it removes the dimension that contains just 1 element
ts_ = ts.squeeze()
ts2_ = ts2.squeeze()
print(ts_.shape)
print(ts2_.shape)
print('ts_---', ts_)
print('ts2_ -- ', ts2_)

torch.Size([3, 2, 4])
torch.Size([3, 2, 4])
ts_--- tensor([[[0.9386, 0.6012, 0.5303, 0.7843],
         [0.8394, 0.4244, 0.4194, 0.1063]],

        [[0.3133, 0.3022, 0.3979, 0.7755],
         [0.2900, 0.1487, 0.4358, 0.0227]],

        [[0.0964, 0.1017, 0.2687, 0.8158],
         [0.1051, 0.6783, 0.4959, 0.2609]]])
ts2_ --  tensor([[[0.9386, 0.6012, 0.5303, 0.7843],
         [0.8394, 0.4244, 0.4194, 0.1063]],

        [[0.3133, 0.3022, 0.3979, 0.7755],
         [0.2900, 0.1487, 0.4358, 0.0227]],

        [[0.0964, 0.1017, 0.2687, 0.8158],
         [0.1051, 0.6783, 0.4959, 0.2609]]])


## Reshape Tensor

In [146]:
# reshapes the tensor to whatever dimension you desire...
# the only (obvious) constraint is the resulting tensor should have equal number of elements as the original
print(t.shape)
print(t.reshape((6,4)))
print(t.reshape((3,1,2,4)))

torch.Size([3, 2, 4])
tensor([[0.9386, 0.6012, 0.5303, 0.7843],
        [0.8394, 0.4244, 0.4194, 0.1063],
        [0.3133, 0.3022, 0.3979, 0.7755],
        [0.2900, 0.1487, 0.4358, 0.0227],
        [0.0964, 0.1017, 0.2687, 0.8158],
        [0.1051, 0.6783, 0.4959, 0.2609]])
tensor([[[[0.9386, 0.6012, 0.5303, 0.7843],
          [0.8394, 0.4244, 0.4194, 0.1063]]],


        [[[0.3133, 0.3022, 0.3979, 0.7755],
          [0.2900, 0.1487, 0.4358, 0.0227]]],


        [[[0.0964, 0.1017, 0.2687, 0.8158],
          [0.1051, 0.6783, 0.4959, 0.2609]]]])


## Transpose of Tensor

In [147]:
t = torch.tensor([[ [1,2,3,4], [5,6,7,8], [9, 10, 11,12] ], [ [-1,-2,-3,-4], [-5,-6,-7,-8], [-9, -10, -11,-12] ]])

In [148]:
print(t.shape)

torch.Size([2, 3, 4])


In [149]:
t.transpose(0,1)

tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  9,  10,  11,  12],
         [ -9, -10, -11, -12]]])

In [150]:
t.shape

torch.Size([2, 3, 4])

## Permute Tensor

In [151]:
# this operation allows user to simultaneously reorder the dimensions unlike transpose which interchanges two dimensions only..
t.permute(2,0,1)

tensor([[[  1,   5,   9],
         [ -1,  -5,  -9]],

        [[  2,   6,  10],
         [ -2,  -6, -10]],

        [[  3,   7,  11],
         [ -3,  -7, -11]],

        [[  4,   8,  12],
         [ -4,  -8, -12]]])

## Tensor Stack and Repeat
- Cat
- Stack
- Repeat
- Repeat Interleave
- Padding

In [152]:
# Tensor cat

t1 = torch.rand(size=(2,3,4))
t2 = torch.rand(size=(2,3,4))
t3 = torch.rand(size=(1,3,4))
t4 = torch.rand(size=(2,3,1))


print(t1)
print(t2)
print(t3)
print(t4)



print('Concatenating Tensors --- \n')

# the dimension where you are concatenating can have different magnitude whereas the others should be same...
print(torch.cat([t1,t2], dim=1))
print(torch.cat([t1,t3], dim=0).shape)
print(torch.cat([t1,t2,t4], dim=2))

tensor([[[0.6625, 0.8781, 0.0225, 0.8279],
         [0.2605, 0.5826, 0.5192, 0.7869],
         [0.1114, 0.1639, 0.4665, 0.7896]],

        [[0.0864, 0.0539, 0.8818, 0.5420],
         [0.1730, 0.5981, 0.6145, 0.6166],
         [0.9026, 0.1659, 0.5595, 0.6078]]])
tensor([[[0.6596, 0.1286, 0.2853, 0.6162],
         [0.2764, 0.4114, 0.3086, 0.3067],
         [0.4425, 0.0677, 0.1520, 0.3750]],

        [[0.1955, 0.4960, 0.7348, 0.3624],
         [0.7998, 0.1334, 0.3391, 0.4908],
         [0.9624, 0.4367, 0.1231, 0.1211]]])
tensor([[[0.2961, 0.8353, 0.4500, 0.2466],
         [0.9152, 0.4115, 0.7656, 0.3548],
         [0.2351, 0.7980, 0.5937, 0.1652]]])
tensor([[[0.2594],
         [0.6242],
         [0.3507]],

        [[0.2352],
         [0.4772],
         [0.4400]]])
Concatenating Tensors --- 

tensor([[[0.6625, 0.8781, 0.0225, 0.8279],
         [0.2605, 0.5826, 0.5192, 0.7869],
         [0.1114, 0.1639, 0.4665, 0.7896],
         [0.6596, 0.1286, 0.2853, 0.6162],
         [0.2764, 0.4114, 0

In [153]:
# Tensor Stack..
# this can be imagined as a combination of unsqueeze and cat...

t1 = torch.rand(size=(3,4))
t2 = torch.rand(size=(3,4))

print(t1)
print(t2)

print(torch.stack([t1,t2], dim=0).shape)
print(torch.stack([t1,t2], dim=0))

print(torch.stack([t1,t2], dim=1).shape)
print(torch.stack([t1,t2], dim=1))

tensor([[0.4956, 0.0049, 0.3513, 0.7247],
        [0.8018, 0.4550, 0.4759, 0.1726],
        [0.5145, 0.5600, 0.0705, 0.2398]])
tensor([[0.3805, 0.2092, 0.9336, 0.3329],
        [0.9134, 0.6427, 0.2649, 0.1939],
        [0.6339, 0.1430, 0.3025, 0.9258]])
torch.Size([2, 3, 4])
tensor([[[0.4956, 0.0049, 0.3513, 0.7247],
         [0.8018, 0.4550, 0.4759, 0.1726],
         [0.5145, 0.5600, 0.0705, 0.2398]],

        [[0.3805, 0.2092, 0.9336, 0.3329],
         [0.9134, 0.6427, 0.2649, 0.1939],
         [0.6339, 0.1430, 0.3025, 0.9258]]])
torch.Size([3, 2, 4])
tensor([[[0.4956, 0.0049, 0.3513, 0.7247],
         [0.3805, 0.2092, 0.9336, 0.3329]],

        [[0.8018, 0.4550, 0.4759, 0.1726],
         [0.9134, 0.6427, 0.2649, 0.1939]],

        [[0.5145, 0.5600, 0.0705, 0.2398],
         [0.6339, 0.1430, 0.3025, 0.9258]]])


In [154]:
# Tensor Repeat

t = torch.rand(3)
print(t)

print(t.repeat(4,2))
print(t.repeat(4,2,3))

tensor([0.0216, 0.8488, 0.6901])
tensor([[0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901],
        [0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901],
        [0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901],
        [0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901]])
tensor([[[0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901, 0.0216, 0.8488,
          0.6901],
         [0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901, 0.0216, 0.8488,
          0.6901]],

        [[0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901, 0.0216, 0.8488,
          0.6901],
         [0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901, 0.0216, 0.8488,
          0.6901]],

        [[0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901, 0.0216, 0.8488,
          0.6901],
         [0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901, 0.0216, 0.8488,
          0.6901]],

        [[0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901, 0.0216, 0.8488,
          0.6901],
         [0.0216, 0.8488, 0.6901, 0.0216, 0.8488, 0.6901, 0.0216, 0.8488,
   

In [155]:
# Tensor Repeat Interleave

t1 = torch.rand(3)
t2 = torch.rand(size = (3,2))

print('Org t1:')
print(t1)
print('Org t2:')
print(t2)

# repeat_interleave is going to repeat each of the elements parameter number of times 
# unlike repeat which repeats the entire structure
print(t1.repeat_interleave(2))


print(t2.repeat_interleave(3, dim=1))
print(t2.repeat_interleave(3, dim=0))

Org t1:
tensor([0.6060, 0.1308, 0.8215])
Org t2:
tensor([[0.3820, 0.8797],
        [0.6807, 0.5212],
        [0.6259, 0.2979]])
tensor([0.6060, 0.6060, 0.1308, 0.1308, 0.8215, 0.8215])
tensor([[0.3820, 0.3820, 0.3820, 0.8797, 0.8797, 0.8797],
        [0.6807, 0.6807, 0.6807, 0.5212, 0.5212, 0.5212],
        [0.6259, 0.6259, 0.6259, 0.2979, 0.2979, 0.2979]])
tensor([[0.3820, 0.8797],
        [0.3820, 0.8797],
        [0.3820, 0.8797],
        [0.6807, 0.5212],
        [0.6807, 0.5212],
        [0.6807, 0.5212],
        [0.6259, 0.2979],
        [0.6259, 0.2979],
        [0.6259, 0.2979]])


In [156]:
# Tensor Padding
from torch.nn import functional as F

x = torch.rand(size=(4,4))
print(x)

tensor([[0.1775, 0.3104, 0.8195, 0.3018],
        [0.5736, 0.3452, 0.0617, 0.8370],
        [0.5715, 0.5437, 0.2433, 0.7548],
        [0.8215, 0.5852, 0.6641, 0.3414]])


In [157]:
pl = 1
pr = 2
pt = 1
pb = 2

a = F.pad(x, (pl, pr, pt, pb), mode = 'constant')
print(a)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.1775, 0.3104, 0.8195, 0.3018, 0.0000, 0.0000],
        [0.0000, 0.5736, 0.3452, 0.0617, 0.8370, 0.0000, 0.0000],
        [0.0000, 0.5715, 0.5437, 0.2433, 0.7548, 0.0000, 0.0000],
        [0.0000, 0.8215, 0.5852, 0.6641, 0.3414, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])


## Mathematical Operations

- Pointwise/Elementwise operations
- Reduction Operations
- Comparison Operations
- Vector/Matrix Operations

In [158]:
# Pointwise/Elementwise operations

t1 = torch.rand(5)
t2 = torch.rand(5)
t3 = torch.rand(size=(3,4))
t4 = torch.rand(size=(3,4))
t5 = torch.rand(size=(3,1))


print('Og t1- ', t1)
print('Og t2- ', t2)
print('Og t3- ', t3)
print('Og t4- ', t4)
print('Og t5- ', t5)


# Adding Scalar
print('t1 + 10:', t1+10)

# Multiply Scalar
print('t1 * 10:', t1*10)
print('t1 * 10:', t1*-10)

# Multiply Scalar abs
print('abs(t1 * -10):', abs(t1*-10))

# Adding MultiDimensional
print('t1 + t2:', t1+t2)
print('t3 + t4:', t3+t4)


#Broadcasting
print('t3+t5:', t3+t5)

Og t1-  tensor([0.1773, 0.2606, 0.4819, 0.7804, 0.1873])
Og t2-  tensor([0.0454, 0.5041, 0.2461, 0.1195, 0.0329])
Og t3-  tensor([[0.6535, 0.8127, 0.6991, 0.0733],
        [0.7591, 0.6668, 0.5696, 0.0840],
        [0.4619, 0.1177, 0.0300, 0.0832]])
Og t4-  tensor([[0.3595, 0.3636, 0.5845, 0.5477],
        [0.3728, 0.3605, 0.9671, 0.7439],
        [0.7362, 0.0705, 0.5959, 0.2142]])
Og t5-  tensor([[0.0484],
        [0.7566],
        [0.9041]])
t1 + 10: tensor([10.1773, 10.2606, 10.4819, 10.7804, 10.1873])
t1 * 10: tensor([1.7734, 2.6060, 4.8186, 7.8044, 1.8730])
t1 * 10: tensor([-1.7734, -2.6060, -4.8186, -7.8044, -1.8730])
abs(t1 * -10): tensor([1.7734, 2.6060, 4.8186, 7.8044, 1.8730])
t1 + t2: tensor([0.2227, 0.7647, 0.7280, 0.9000, 0.2202])
t3 + t4: tensor([[1.0130, 1.1763, 1.2836, 0.6211],
        [1.1319, 1.0274, 1.5367, 0.8278],
        [1.1981, 0.1881, 0.6258, 0.2973]])
t3+t5: tensor([[0.7019, 0.8612, 0.7476, 0.1218],
        [1.5156, 1.4234, 1.3262, 0.8405],
        [1.3659, 1.0

## Reduction Operations
- sum(), mean(), std(), max(), argmax(), prod(), unique(), etc.

In [159]:
t1 = torch.rand(3)
t2=  torch.rand(size=(3,4))

In [160]:
print(t1.sum())
print(t2.sum())
print(t2.sum(axis=0))
print(t2.sum(axis=1))

tensor(2.3705)
tensor(5.5003)
tensor([1.8907, 0.6995, 1.3178, 1.5924])
tensor([0.6016, 2.5863, 2.3124])


## Vector/Matrix Multiplication 

In [161]:
# vector vector
t1 = torch.randn(3)
t2 = torch.randn(3)

print('t1: ', t1)
print('t2: ', t2)

print(torch.matmul(t1,t2))

# matrix vector
t1 = torch.randn(size=(3,4))
t2 = torch.randn(4)


# print(t1.shape)

print('t1: ', t1)
print('t2: ', t2)

print(torch.matmul(t1,t2))


# batched matrix vector product... tensor vector product
t1 = torch.randn(size=(10,3,4))
t2 = torch.randn(4)

print('t1: ', t1)
print('t2: ', t2)

print(torch.matmul(t1,t2))
print(torch.matmul(t1,t2).shape)


# batched matrix x batched matrix ... tensor tensor product
t1 = torch.randn(size=(5,3,4))
t2 = torch.randn(size=(5,4,5))

print('t1: ', t1)
print('t2: ', t2)

print(torch.matmul(t1,t2))
print(torch.matmul(t1,t2).shape)



# batched matrix x  matrix broadcast ... tensor matrix product
t1 = torch.randn(size=(5,3,4))
t2 = torch.randn(size=(4,5))

print('t1: ', t1)
print('t2: ', t2)

print(torch.matmul(t1,t2))
print(torch.matmul(t1,t2).shape)

t1:  tensor([-0.7208,  1.0367,  1.1439])
t2:  tensor([-0.1440,  0.4236, -1.3845])
tensor(-1.0408)
t1:  tensor([[-0.8738, -0.4117, -0.5638, -0.8933],
        [ 1.7017, -1.4210, -0.5414,  2.5009],
        [ 0.1846, -0.8707,  0.7558,  0.9361]])
t2:  tensor([-0.0126, -0.9901, -0.6250, -0.7893])
tensor([ 1.4761, -0.2501, -0.3516])
t1:  tensor([[[-0.0843,  0.2812, -0.9655,  2.2886],
         [ 1.6782,  3.3757,  0.3611, -1.5963],
         [-0.3027,  1.1092,  0.5644,  1.2007]],

        [[-0.3929, -0.4397, -0.0712,  0.1361],
         [ 1.2986, -0.8196,  0.8388, -0.2275],
         [ 0.8579, -0.7283,  0.3293,  0.8370]],

        [[ 0.5573,  1.3280, -0.0443,  0.4435],
         [ 1.4461, -0.5020,  0.7246, -0.2111],
         [-0.8350,  0.1041, -0.9301, -0.7072]],

        [[ 2.1066, -0.8506, -1.8685,  0.1710],
         [ 0.0779, -0.6455,  0.4126, -1.1686],
         [ 0.5102,  1.6656,  0.7671, -0.9117]],

        [[ 1.0846, -0.1212, -2.1470, -1.3972],
         [ 0.5527, -0.3682,  0.2245, -1.7338],
 